import type { Metadata } from "next";
import Image from "next/image";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <header className="flex items-center space-x-8 bg-secondary-light p-4">
        <Image
          alt="pokemon logo"
          src="https://www.freepnglogos.com/uploads/pokemon-symbol-logo-png-31.png"
          width={40}
          height={40}
        />
        <p className="text-3xl">Pokemons</p>
      </header>
      {children}
      <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
        <p>Footer</p>
      </footer>
    </>
  );
}
